# Generated by Django 3.2.2 on 2021-05-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(default='hollywood', max_length=255)),
                ('category', models.CharField(default='adventure', max_length=255)),
                ('logo_link', models.CharField(default='https://parrotsec.org/images/about/notebook.png', max_length=255)),
                ('screen_shots', models.CharField(default='https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png ', max_length=300)),
                ('title', models.CharField(default='temp', max_length=255)),
                ('title_caption', models.CharField(default='this is the caption for title', max_length=100)),
                ('content', models.TextField(default='this i isis fd jfl jfjsal dsj oif ds fdjfk dlkjdsfk dsjfkl dsdflk dslkdsjflk dlkjflkds flk jdsflkdsjflkjfoier jfd.,j fl dsjflkjsod')),
                ('download_links', models.CharField(default=' {"480":"https://480", "720":"https://720","1080":"https://1080"}', max_length=300)),
                ('trailer_link', models.CharField(default='https://tralerss', max_length=100)),
                ('best', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
