# Generated by Django 3.2.2 on 2021-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_remove_post_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='please',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
