# Generated by Django 3.2.2 on 2021-05-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0003_post_please'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='please',
        ),
    ]
