# Generated by Django 3.2.2 on 2021-05-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0004_remove_post_please'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='screen_shots',
            field=models.CharField(default='https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png ', max_length=1000),
        ),
    ]
