# Generated by Django 3.2.2 on 2021-05-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0006_auto_20210527_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_caption',
            field=models.TextField(default='this is the caption for title'),
        ),
    ]
