# Generated by Django 3.2.2 on 2021-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0007_alter_post_title_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(default='adventure'),
        ),
        migrations.AlterField(
            model_name='post',
            name='download_links',
            field=models.TextField(default=' {"480":"https://480", "720":"https://720","1080":"https://1080"}'),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo_link',
            field=models.TextField(default='https://parrotsec.org/images/about/notebook.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='screen_shots',
            field=models.TextField(default='https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png https://parrotsec.org/images/about/notebook.png '),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.TextField(default='hollywood'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='temp'),
        ),
        migrations.AlterField(
            model_name='post',
            name='trailer_link',
            field=models.TextField(default='https://tralerss'),
        ),
    ]
