# Generated by Django 3.2.1 on 2021-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0009_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ips',
            field=models.TextField(default='127.0.0.1,'),
        ),
    ]
