# Generated by Django 3.2.1 on 2021-06-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0011_post_keyworlds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='keyworlds',
            new_name='keywords',
        ),
    ]
