# Generated by Django 3.2.1 on 2021-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('content', models.TextField()),
            ],
        ),
    ]
